2024-11-01 09:41:54,855 INFO    MainThread:51410 [wandb_setup.py:_flush():79] Current SDK version is 0.18.5
2024-11-01 09:41:54,855 INFO    MainThread:51410 [wandb_setup.py:_flush():79] Configure stats pid to 51410
2024-11-01 09:41:54,856 INFO    MainThread:51410 [wandb_setup.py:_flush():79] Loading settings from /Users/estanislaorioszgaib/.config/wandb/settings
2024-11-01 09:41:54,856 INFO    MainThread:51410 [wandb_setup.py:_flush():79] Loading settings from /Users/estanislaorioszgaib/Desktop/TP3-TD6/TP3_TD6_repo/wandb/settings
2024-11-01 09:41:54,856 INFO    MainThread:51410 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-11-01 09:41:54,856 INFO    MainThread:51410 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-11-01 09:41:54,856 INFO    MainThread:51410 [wandb_setup.py:_flush():79] Applying login settings: {'api_key': '***REDACTED***'}
2024-11-01 09:41:54,856 INFO    MainThread:51410 [wandb_setup.py:_flush():79] Applying login settings: {'api_key': '***REDACTED***'}
2024-11-01 09:41:54,856 INFO    MainThread:51410 [wandb_setup.py:_flush():79] Applying login settings: {'api_key': '***REDACTED***'}
2024-11-01 09:41:54,856 INFO    MainThread:51410 [wandb_setup.py:_flush():79] Applying login settings: {'api_key': '***REDACTED***'}
2024-11-01 09:41:54,856 INFO    MainThread:51410 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-11-01 09:41:54,856 INFO    MainThread:51410 [wandb_init.py:_log_setup():534] Logging user logs to /Users/estanislaorioszgaib/Desktop/TP3-TD6/TP3_TD6_repo/wandb/run-20241101_094154-m1jd6tsl/logs/debug.log
2024-11-01 09:41:54,856 INFO    MainThread:51410 [wandb_init.py:_log_setup():535] Logging internal logs to /Users/estanislaorioszgaib/Desktop/TP3-TD6/TP3_TD6_repo/wandb/run-20241101_094154-m1jd6tsl/logs/debug-internal.log
2024-11-01 09:41:54,856 INFO    MainThread:51410 [wandb_init.py:init():621] calling init triggers
2024-11-01 09:41:54,856 INFO    MainThread:51410 [wandb_init.py:init():628] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.002, 'batch_size': 20, 'epochs': 500, 'subset_train': 1200, 'subset_val': 200}
2024-11-01 09:41:54,856 INFO    MainThread:51410 [wandb_init.py:init():671] starting backend
2024-11-01 09:41:54,856 INFO    MainThread:51410 [wandb_init.py:init():675] sending inform_init request
2024-11-01 09:41:54,861 INFO    MainThread:51410 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-11-01 09:41:54,862 INFO    MainThread:51410 [wandb_init.py:init():688] backend started and connected
2024-11-01 09:41:54,869 INFO    MainThread:51410 [wandb_run.py:_label_probe_notebook():1342] probe notebook
2024-11-01 09:41:54,871 INFO    MainThread:51410 [wandb_init.py:init():783] updated telemetry
2024-11-01 09:41:54,897 INFO    MainThread:51410 [wandb_init.py:init():816] communicating run to backend with 90.0 second timeout
2024-11-01 09:43:25,263 ERROR   MainThread:51410 [wandb_init.py:init():842] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-11-01 09:43:25,266 ERROR   MainThread:51410 [wandb_init.py:init():1266] error in wandb.init()
Traceback (most recent call last):
  File "/opt/anaconda3/envs/TD6/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1256, in init
    return wi.init()
           ^^^^^^^^^
  File "/opt/anaconda3/envs/TD6/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 848, in init
    raise error
wandb.errors.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
